apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::154328642498:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-KBN1T4T8BXNA
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-09T06:26:05Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1744"
  uid: 75c3d6f6-acd1-4c43-be15-3c3b7276f379
